- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Persist timezone to /etc/timezone
  ansible.builtin.command: dpkg-reconfigure --frontend noninteractive tzdata
  changed_when: false

- name: Install basic packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      # package manager utilities
      - apt-transport-https
      - software-properties-common
      # TERM screen-256color-bce
      - ncurses-term
      # enhanced editor
      - vim
      - nano
      # process observation tools
      - htop
      # web tools
      - curl
      - wget
      # shell completion
      - bash-completion
      # pip
      - python3-pip
      # logger, wall. etc.
      - bsdutils
      # dig, nslookup, etc.
      - dnsutils
      # GNU Privacy Guard
      - gpg
      # file transfer
      - rsync
      # terminal multiplexer
      - screen
      # compressor
      - bzip2
      - gzip
      - tar
      - unrar-free
      - unzip
      - xz-utils
      # JSON processor
      - jq
      # YAML processor
      - yq

- name: Install additional packages
  ansible.builtin.apt:
    name: "{{ common_install_packages }}"
    state: present
    update_cache: true

- name: Remove unused packages
  ansible.builtin.apt:
    name: "{{ common_remove_packages }}"
    state: absent
    update_cache: true
